language: rust
os:
    - windows
    - linux
    - osx
rust:
#  - stable
#  - beta
  - nightly
#matrix:
#  allow_failures:
#    - rust: nightly
addons:
  apt:
    packages:
      - libasound2-dev
script:
    - cargo test
