cargo-features = ["edition"]
[package]
name = "remani"
version = "0.1.0"
authors = ["Matthew Tran <0e4ef622@gmail.com>"]
edition = '2018'

[dependencies]
piston = "0.37.0"
piston-texture = "0.6.0"
pistoncore-glutin_window = "0.47.0"
piston2d-graphics = "0.26.0"
piston2d-opengl_graphics = "0.53.0"
image = "0.19.0"
cpal = { git = "https://github.com/0e4ef622/cpal", rev = "buffer-size-request" }
simplemad = { optional = true, version = "0.9.0" }

[features]
default = ["mp3"]
mp3 = ["simplemad"]
