[workspace]
members = [
    "src/audio",
    "src/chart",
    "src/config",
    "src/gameskin",
    "src/judgement",
    "src/remani",
    "src/warn",
]

[patch.crates-io]
cpal = { git = "https://github.com/0e4ef622/cpal", rev = "buffer-size-request" }
conrod = { git = "https://github.com/0e4ef622/conrod", rev = "rebase" } # my piston dpi patch rebased on a pull request to update conrod's dependencies

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
